version: "3.8"
services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3002:4173"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:4173"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always
