version: "3.8"
services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3002:4173" # Maps admin service to port 3002
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Maps backend service to port 3000
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:4173" # Maps frontend service to port 3001
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
